### ISSUE TITLE
Add <require> to usage instructions in Readme

### ISSUE THREAD

**Issue by gordon-matt** [aurelia-contrib/aurelia-dynamic-html#2]
It's probably obvious to most already, but just for completeness, I think it would be good to mention under **Usage** in your instructions, that we need to require the plugin as follows:

`<require from="aurelia-dynamic-html/aurelia-dynamic-html"></require>`

**Comment by fkleuver** [comment]
The element shouldn't need to be explicitly required.

Did you configure the plugin with `au.use.plugin(PLATFORM.moduleName("aurelia-dynamic-html"))`? 

Are you using webpack or aurelia-cli?

**Comment by gordon-matt** [comment]
Oops, my mistake. I am using JSPM, but that doesn't matter, because to be honest, I didn't try without the require element. I am still quite new to Aurelia and I assumed I would need to always do that unless something was put in the `globalResources` section in the **main.js**. It seems it works just fine without that, so I will close this issue.
